package seeders

import (
	"github.com/goravel/framework/facades"

	"goravel/app/models"
)

type CurrencySeeder struct {
}

func (s *CurrencySeeder) Signature() string {
	return "CurrencySeeder"
}

func (s *CurrencySeeder) Run() error {
	// 创建常用货币（按流行度排序）
	currencies := []models.Currency{
		// 法币（按使用频率和重要性排序）
		{
			Code:          "CNY",
			Name:          "人民币",
			Symbol:        "¥",
			Rate:          1.0,
			DecimalPlaces: 2,
			IsDefault:     true,
			IsActive:      true,
			Sort:          1,
			Description:   "中国人民币，基准货币",
		},
		{
			Code:          "USD",
			Name:          "美元",
			Symbol:        "$",
			Rate:          7.2,
			DecimalPlaces: 2,
			IsDefault:     false,
			IsActive:      true,
			Sort:          2,
			Description:   "美国美元",
		},
		{
			Code:          "EUR",
			Name:          "欧元",
			Symbol:        "€",
			Rate:          7.8,
			DecimalPlaces: 2,
			IsDefault:     false,
			IsActive:      true,
			Sort:          3,
			Description:   "欧洲欧元",
		},
		{
			Code:          "GBP",
			Name:          "英镑",
			Symbol:        "£",
			Rate:          9.1,
			DecimalPlaces: 2,
			IsDefault:     false,
			IsActive:      true,
			Sort:          4,
			Description:   "英国英镑",
		},
		{
			Code:          "JPY",
			Name:          "日元",
			Symbol:        "¥",
			Rate:          0.05,
			DecimalPlaces: 0, // 日元没有小数
			IsDefault:     false,
			IsActive:      true,
			Sort:          5,
			Description:   "日本日元",
		},
		{
			Code:          "HKD",
			Name:          "港币",
			Symbol:        "HK$",
			Rate:          0.92,
			DecimalPlaces: 2,
			IsDefault:     false,
			IsActive:      true,
			Sort:          6,
			Description:   "香港港币",
		},
		{
			Code:          "THB",
			Name:          "泰铢",
			Symbol:        "฿",
			Rate:          0.20,
			DecimalPlaces: 2,
			IsDefault:     false,
			IsActive:      true,
			Sort:          7,
			Description:   "Thai Baht，泰铢",
		},
		{
			Code:          "INR",
			Name:          "印度卢比",
			Symbol:        "₹",
			Rate:          0.086,
			DecimalPlaces: 2,
			IsDefault:     false,
			IsActive:      true,
			Sort:          8,
			Description:   "Indian Rupee，印度卢比",
		},
		{
			Code:          "VND",
			Name:          "越南盾",
			Symbol:        "₫",
			Rate:          0.0003,
			DecimalPlaces: 0, // 越南盾通常没有小数
			IsDefault:     false,
			IsActive:      true,
			Sort:          9,
			Description:   "Vietnamese Dong，越南盾",
		},
		// 虚拟货币（按市值和流行度排序，统一使用8位小数）
		{
			Code:          "BTC",
			Name:          "比特币",
			Symbol:        "₿",
			Rate:          450000.0,
			DecimalPlaces: 8,
			IsDefault:     false,
			IsActive:      true,
			Sort:          10,
			Description:   "Bitcoin，比特币",
		},
		{
			Code:          "ETH",
			Name:          "以太坊",
			Symbol:        "Ξ",
			Rate:          28000.0,
			DecimalPlaces: 8,
			IsDefault:     false,
			IsActive:      true,
			Sort:          11,
			Description:   "Ethereum，以太坊",
		},
		{
			Code:          "USDT",
			Name:          "泰达币",
			Symbol:        "₮",
			Rate:          7.2,
			DecimalPlaces: 8,
			IsDefault:     false,
			IsActive:      true,
			Sort:          12,
			Description:   "Tether，泰达币，稳定币",
		},
		{
			Code:          "BNB",
			Name:          "币安币",
			Symbol:        "BNB",
			Rate:          3500.0,
			DecimalPlaces: 8,
			IsDefault:     false,
			IsActive:      true,
			Sort:          13,
			Description:   "Binance Coin，币安币",
		},
		{
			Code:          "SOL",
			Name:          "Solana",
			Symbol:        "◎",
			Rate:          1200.0,
			DecimalPlaces: 8,
			IsDefault:     false,
			IsActive:      true,
			Sort:          14,
			Description:   "Solana，索拉纳",
		},
		{
			Code:          "XRP",
			Name:          "瑞波币",
			Symbol:        "XRP",
			Rate:          5.2,
			DecimalPlaces: 8,
			IsDefault:     false,
			IsActive:      true,
			Sort:          15,
			Description:   "Ripple，瑞波币",
		},
		{
			Code:          "USDC",
			Name:          "USD Coin",
			Symbol:        "USDC",
			Rate:          7.2,
			DecimalPlaces: 8,
			IsDefault:     false,
			IsActive:      true,
			Sort:          16,
			Description:   "USD Coin，美元稳定币",
		},
		{
			Code:          "ADA",
			Name:          "艾达币",
			Symbol:        "₳",
			Rate:          4.5,
			DecimalPlaces: 8,
			IsDefault:     false,
			IsActive:      true,
			Sort:          17,
			Description:   "Cardano，艾达币",
		},
		{
			Code:          "DOGE",
			Name:          "狗狗币",
			Symbol:        "Ð",
			Rate:          0.55,
			DecimalPlaces: 8,
			IsDefault:     false,
			IsActive:      true,
			Sort:          18,
			Description:   "Dogecoin，狗狗币",
		},
		{
			Code:          "TRX",
			Name:          "波场币",
			Symbol:        "TRX",
			Rate:          0.65,
			DecimalPlaces: 8,
			IsDefault:     false,
			IsActive:      true,
			Sort:          19,
			Description:   "TRON，波场币",
		},
		{
			Code:          "DOT",
			Name:          "波卡币",
			Symbol:        "●",
			Rate:          45.0,
			DecimalPlaces: 8,
			IsDefault:     false,
			IsActive:      true,
			Sort:          20,
			Description:   "Polkadot，波卡币",
		},
		{
			Code:          "MATIC",
			Name:          "Polygon",
			Symbol:        "MATIC",
			Rate:          6.8,
			DecimalPlaces: 8,
			IsDefault:     false,
			IsActive:      true,
			Sort:          21,
			Description:   "Polygon，马蹄币",
		},
		{
			Code:          "LTC",
			Name:          "莱特币",
			Symbol:        "Ł",
			Rate:          680.0,
			DecimalPlaces: 8,
			IsDefault:     false,
			IsActive:      true,
			Sort:          22,
			Description:   "Litecoin，莱特币",
		},
		{
			Code:          "AVAX",
			Name:          "雪崩币",
			Symbol:        "AVAX",
			Rate:          280.0,
			DecimalPlaces: 8,
			IsDefault:     false,
			IsActive:      true,
			Sort:          23,
			Description:   "Avalanche，雪崩币",
		},
		{
			Code:          "LINK",
			Name:          "Chainlink",
			Symbol:        "LINK",
			Rate:          120.0,
			DecimalPlaces: 8,
			IsDefault:     false,
			IsActive:      true,
			Sort:          24,
			Description:   "Chainlink，链环币",
		},
		{
			Code:          "UNI",
			Name:          "Uniswap",
			Symbol:        "UNI",
			Rate:          45.0,
			DecimalPlaces: 8,
			IsDefault:     false,
			IsActive:      true,
			Sort:          25,
			Description:   "Uniswap，独角兽币",
		},
		{
			Code:          "ATOM",
			Name:          "Cosmos",
			Symbol:        "ATOM",
			Rate:          85.0,
			DecimalPlaces: 8,
			IsDefault:     false,
			IsActive:      true,
			Sort:          26,
			Description:   "Cosmos，原子币",
		},
		{
			Code:          "ETC",
			Name:          "以太经典",
			Symbol:        "ETC",
			Rate:          180.0,
			DecimalPlaces: 8,
			IsDefault:     false,
			IsActive:      true,
			Sort:          27,
			Description:   "Ethereum Classic，以太经典",
		},
	}

	for _, currency := range currencies {
		// 使用 FirstOrCreate：如果不存在则创建，存在则跳过
		facades.Orm().Query().Where("code", currency.Code).FirstOrCreate(&currency, currency)
	}

	return nil
}
